### ISSUE TITLE
Missing ~/scripts dir

### ISSUE THREAD

**Issue by chocopowwwa** [rmw5601/dotfiles#1]
Hi! thank you for sharing your config, i really like it. but the `~/scripts` dir is missing, do you mind sharing your `~/scripts` ? thank you :D

**Comment by iiPlasma** [comment]
Ye same thing as @chocopowwwa, I wanted to replicate the polybar of this but the ~/scripts dir is missing. Would love if you just took a few minutes to add it. Thanks c:

**Comment by rmw5601** [comment]
They are not missing. They are in a separate repo and my polybar doesn't rely on `~/scripts`

**Comment by chocopowwwa** [comment]
@rmw5601 thank you :drooling_face:
