### ISSUE TITLE
Polybar

### ISSUE THREAD

**Issue by iiPlasma** [rmw5601/dotfiles#2]
i copied your polybar setup exactly, but the play pause and next buttons don't work. I think mpc and mpd aren't running on the same port or something. I had to change mpd and ncmpcpp port to 6610, is that maybe why when I try mpc next it says mpd error: not playing? If so, how do I change the port for mpc? I tried googling but couldn't find anything

**Comment by rmw5601** [comment]
This has nothing to do with me.
